### ISSUE TITLE
string indices must be integers (vin = vehicle["vin"])

### ISSUE THREAD

**Issue by barto64** [CJNE/ha-porscheconnect#112]
## Version of the custom_component

V0.0.9

## Configuration

``There are not config parameters``

## Describe the bug

Integration has stopped working and the below log shows a problem in the code probably due to a change of Porsche in their API

## Debug log

``2022-09-14 21:37:22.220 ERROR (MainThread) [custom_components.porscheconnect] Unexpected error fetching porscheconnect data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 175, in _async_update_data
    vin = vehicle["vin"]
TypeError: string indices must be integers``

**Comment by browetd** [comment]
Same problem... This appeared when I installed the latest version oh Home Assistant... but not sure it is linked... Maybe a change on the API side...

**Comment by fredriklj** [comment]
Addressed here:

https://github.com/CJNE/pyporscheconnectapi/pull/18

**Comment by barto64** [comment]
That's nice, but now, if i am not wrong, someone (knidly :)) need to apply similar changes to this HA Custom Component

**Comment by CJNE** [comment]
Fixed in version 0.0.10, thanks @fredriklj !

**Comment by barto64** [comment]
Great thanks for the super prompt response.
