### ISSUE TITLE
Integration does no longer work after PCM upgrade - can be Closed

### ISSUE THREAD

**Issue by midget1234** [CJNE/ha-porscheconnect#126]
After the upgrade to PCM 6 (the 'colored icons' update) the integration is no longer working.

Error message:

Logger: custom_components.porscheconnect
Source: custom_components/porscheconnect/__init__.py:175
Integration: Porsche Connect (documentation, issues)
First occurred: 20:01:37 (13 occurrences)
Last logged: 20:14:07

Unexpected error fetching porscheconnect data: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/porscheconnect/__init__.py", line 175, in _async_update_data
    vin = vehicle["vin"]
TypeError: string indices must be integers

**Comment by michaelf988** [comment]
Exactly the same issue here.

**Comment by CJNE** [comment]
I would need some help on this one as I don't have access to a car with PCM 6.
Can someone install the python library and do a `porschecli list`? Looks like the output format might have changed with PCM 6 and I need to figure out in what way...

**Comment by midget1234** [comment]
Happy to help, but this is already beyond my capabilities. I sthere another way to get you the Output format ?

**Comment by jfrigger** [comment]
hi! if that helps: i have PCM6 in a taycan MJ22 and it works well. (it was already delivered with PCM6).

But there seems to be an update for PCM6, it is called "WNK1" - you only get this at your dealer, not via OTA according to info from MyPorsche Service. Maybe you have this WNK1 Update already?

**Comment by midget1234** [comment]
I already have WNK1, that is the update (from white icons to coloured) that caused the HA integration to stop working.
Thanks for your comments though. @CNJE: How can we get you a PCM6 car with the WNK1 update ;-)

**Comment by jfrigger** [comment]
actually WNK1 is an update OF the colored icons one. 

i have colored icons one already since delivery, i'll get WNK1 end of january though. curious how we can help to fix this. 

@midget1234 to run porschecli as mentioned by @CJNE, i guess you need to to the following:

- open a new SSH/Terminal session on Home assistant (e.g. through one of the addons)
- run "pip install pyporscheconnectapi" and follow the instructions
- run "sudo porschecli list" afterwards, enter your myporsche credentials when asked
- send @CJNE  the output. 

hope that helps, @CJNE  please confirm the steps :)

**Comment by midget1234** [comment]
I am back in business.. I installed th enew (?) integration that was shown in HACS and this works like a charm. Thanks to the developpers who made changes..  All is working as before WITH the car being updated to latest PCM version.

**Comment by midget1234** [comment]
How can I 'close' this issue ?

**Comment by CJNE** [comment]
Thanks for letting me know, I haven't changed anything so it must have been a temporary problem then :)

**Comment by midget1234** [comment]
Verstuurd vanaf mijn iPhoneOp 4 jan. 2023 om 00:38 heeft Johan Isacsson ***@***.***> het volgende geschreven:﻿Those are the best ones 😁..
Thanks for letting me know, I haven't changed anything so it must have been a temporary problem then :)
