### ISSUE TITLE
Lock/Unlock Function

### ISSUE THREAD

**Issue by midnightsurfer** [CJNE/ha-porscheconnect#146]
Hi, great integration thanks. Lock unlock doesnt seem to function and wondered about how to deal with the likely PIN code issue that is the most likely reason for it not running ? Tried hard coding the PIN in the lock.py code and also same issue when adding the lock to the Alexa and using its optional unlock code feature.  Error in HA is Failed to call service lock/unlock

**Comment by fredriklj** [comment]
The lock.unlock service allows providing the 'code' parameter to enter the PIN. I just tried it, and it works as expected.

**Comment by CJNE** [comment]
Please re-open if the problem persists, but as @fredriklj mentioned you should be able to pass the PIN as a parameter to the service.
