### ISSUE TITLE
Nach Update anmelden nicht mehr möglich Fehler: "connect"

### ISSUE THREAD

**Issue by OM1971** [CJNE/ha-porscheconnect#215]
Nach jedem Update von HA verliert die Integration den Zugang.
Neues anmelden mit den gültigen Zugangsdaten ist nicht möglich.
Immer der Fehler "connect"

Komplettes entfernen der Integration und erneutes hinzufügen bringt keine Änderung.

Anmelden über die Porsche Homepage ist kein Problem.

Hat jemand dieses Problem gelöst?

**Comment by midget1234** [comment]
Exactly the same situation here :-(

**Comment by otw** [comment]
+1 Running into the same issue after upgrading then trying to re-install via HACS/manually. Couldn't find anything in logs even with debug logging enabled globally.

**Comment by fredriklj** [comment]
I can only vaguely understand the problem description above, but it could be related to the captcha issue. Please review the issue here:

https://github.com/CJNE/pyporscheconnectapi/issues/37

If this is your problem, it might help to disable the integration and let it sit overnight before enabling again. Otherwise, try the other solutions suggested there.

**Comment by midget1234** [comment]
I have got mine working again after the updating to the latest version. Working for 2 days now..

**Comment by OM1971** [comment]
Probiere es jeden Tag mit einer kompletten Neuinstallation der Integration.
Immer wieder die gleiche Fehlermeldung.
Funktioniert nicht. Schade.

**Comment by OM1971** [comment]
Mittlerweile kommt der "Connect" Fehler nicht mehr, aber dafür nach erfolgreicher Einrichtung der Integration:
"Einrichtung fehlgeschlagen".

Habe schon alles probiert. Cache geleert, neu heruntergeladen etc.
Läuft nicht.
Sehr ärgerlich. :(

**Comment by fredriklj** [comment]
Can you please try #217

**Comment by Pekah80** [comment]
Solange auf der Webseite von My Porsche ein und ausloggen bis es bei der Anmeldung kein Capture mehr zu lösen gibt. 
Danach sollte der Fehler "Connect" weg sein

**Comment by fredriklj** [comment]
We're back to square one, cf. #242 and reopen any new issues.
