### ISSUE TITLE
Real Time Location Updates

### ISSUE THREAD

**Issue by mbhforum** [CJNE/ha-porscheconnect#226]
**Is your feature request related to a problem? Please describe.**

I am trying to setup automation so when I arrive home with my Taycan, it opens my garage door.  Unfortunately, there is roughly a 10 minute delay with this plug-in for status updates. 

**Describe the solution you'd like**

When my Taycan is marked "Home", I am able to run Home Assistant actions. 

**Describe alternatives you've considered**

**Additional context**

**Comment by fredriklj** [comment]
We're back to square one, cf. #242 and reopen any new issues.
