### ISSUE TITLE
updated to HA2024.2.1 now connect error...

### ISSUE THREAD

**Issue by Racerider101** [CJNE/ha-porscheconnect#234]
Hello. Been working fine, updated to HA2024.2.1 and will now not connect.  Connect app working fine and login details checked..  Any advice on how to resolve please.  Version .18 of component. Thx

**Comment by devdems** [comment]
The same issue happening in my side.

**Comment by fredriklj** [comment]
We're back to square one, cf. #242 and reopen any new issues.
