### ISSUE TITLE
Error message: No devices or entities – Failed setup, will retry, NickName

### ISSUE THREAD

**Issue by Yura-87** [CJNE/ha-porscheconnect#245]
Hello, first of all thank you for this HA extension. When I try to login with My Porsche credentials, which I am using in mobile app, I receive this error message:
![scr](https://github.com/CJNE/ha-porscheconnect/assets/15585200/2c6b6eb1-ec8e-4a70-a42c-a21fa2689df3)

Tried to restart HA, log in again, but still the same results. Porsche Connect is active, I can fully manage my car via the Porsche app. Do you have any idea how to solve this issue?

**Comment by richardcoyle** [comment]
Mine was working fine until recently. Now the same thing is happening to me.

**Comment by MathiasSvDK** [comment]
Same happend for me.

**Comment by Yura-87** [comment]
Looks like Porsche made some changes in their API.

**Comment by f1dgj** [comment]
I’ve got the same issue

**Comment by ronniebach** [comment]
Same here... When will it be fixed ?

**Comment by gadgetbazza** [comment]
New user for this integration here.  Confirming the same issue on my first attempt at connecting.

**Comment by Ayuus** [comment]
I have the same issue, any news on this?

**Comment by fredriklj** [comment]
Please see https://github.com/CJNE/pyporscheconnectapi/issues/46#issuecomment-2210352012

**Comment by jasonhollis** [comment]
Same here

**Comment by patrusco** [comment]
same here

**Comment by fredriklj** [comment]
C.f. #242.
