### ISSUE TITLE
New_api exception: 'Client'object has no attribute 'isTokenRefreshed'

### ISSUE THREAD

**Issue by Ayuus** [CJNE/ha-porscheconnect#248]
After installing the 'new_api' branch (which I could not have done without [this post](https://github.com/CJNE/pyporscheconnectapi/issues/46#issuecomment-2210352012) and [this post](https://www.reddit.com/r/homeassistant/comments/lcur6n/how_to_execute_pip_command_in_home_assistant_vm/), as for some reason, library pyporscheconnectapi was not correct version), I installed the integration.
Starting the integration fails with error message: 'Client'object has no attribute 'isTokenRefreshed'
After commenting out line 209 (`if IsTokenRefreshed():`) in file __init__.py, the integration loaded and I was able to see my car's data.

**Comment by Villersfr2** [comment]
Same for me. It has worked flawlessly during some hours and then stopped.

**Comment by Ayuus** [comment]
Same for me, my "fix" worked for a fwe hours. Then it stopped, and I cannot get it to work again, unfortunately.

**Comment by fredriklj** [comment]
FWIW, I have pushed some changes to the new_api branch which should address the issues you are mentioning. And give you a few more entities in hass.
