### ISSUE TITLE
Einrichtung fehlgeschlagen, wird erneut versucht: 'nickName'

### ISSUE THREAD

**Issue by fr-Fabix** [CJNE/ha-porscheconnect#249]
## Version of the custom_component

0.0.18

## Describe the bug

When I set up the integration, the following message appears: Setup failed, will try again: 'nickName'

I don't know how to get a log or the configuration... Can you please help me?

**Comment by OM1971** [comment]
Dieser Fehler tritt leider schon seit einiger Zeit auf. Bisher keine Besserung in Sicht. Schade, die Integration war immer sehr zuverlässig.

**Comment by fredriklj** [comment]
This integration is currently broken, since porsche dropped the API we used previously. There is a (slow) ongoing effort to adapt to the new API which you can try out in a development environment: 

https://github.com/CJNE/ha-porscheconnect/tree/new_api

This is work-in-progress, expect bugs.
