### ISSUE TITLE
Failed to call service lock/lock. Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by josh-heyman** [CJNE/ha-porscheconnect#82]
Hi. I am new to HA and HACS so forgive me if this is something obvious to fix. When trying to lock or unlock the car I get

```
Failed to call service lock/lock. Expecting value: line 1
column 1 (char 0)
```

Everything else works as expected, range, location, etc

**Comment by CJNE** [comment]
Thanks, will take a look asap

**Comment by fredriklj** [comment]
Addressed here:

https://github.com/CJNE/pyporscheconnectapi/pull/13
