### ISSUE TITLE
Integration not showing up in UI

### ISSUE THREAD

**Issue by sdds250** [CJNE/ha-porscheconnect#93]
## Version:

ha-porscheconnect 0.0.8
core-2022.6.7
Home Assistant OS 8.2
supervisor-2022.05.3

## Configuration

n.a.

## Describe the bug

Not sure it is a integration bug, don't hesitate to delete if it is not the right place.

Installed HACS and added the custom integration, but the integration does not show up in:

### Settings -> 'Devices & Services' -> '+ Add Integration'

<img width="483" alt="Screenshot 2022-06-23 at 21 09 55" src="https://user-images.githubusercontent.com/108091159/175378793-2e54e418-a9b6-4f2a-ad9a-4e1dc9131320.png">

### Custom integration correctly added in HACS:

<img width="1139" alt="Screenshot 2022-06-23 at 21 12 23" src="https://user-images.githubusercontent.com/108091159/175379169-420fbd31-0e05-4bb5-bd75-ed2ea5d096a2.png">

### And present in the custom_components folder:

<img width="288" alt="Screenshot 2022-06-23 at 21 32 17" src="https://user-images.githubusercontent.com/108091159/175382334-6e15eaef-64a6-4fec-9dde-2848871407ee.png">

## Debug log

log I could find (debug level configured, search for word Porsche) :

> 2022-06-23 21:23:39 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration **porsche**connect which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

>  2022-06-23 21:23:47 DEBUG (MainThread) [homeassistant.helpers.translation] Cache miss for en-GB: syncthing, nanoleaf, smhi, hangouts, ukraine_alarm, unifiprotect, blebox, filesize, insteon, aladdin_connect, waze_travel_time, mullvad, totalconnect, tesla_wall_connector, yolink, overkiz, smartthings, version, evil_genius_labs, uptimerobot, ambee, meteoclimatic, yale_smart_alarm, wemo, ridwell, rfxtrx, deconz, spotify, atag, hunterdouglas_powerview, slimproto, openuv, flunearyou, hisense_aehw4a1, life360, luftdaten, hyperion, kaleidescape, vicare, google_travel_time, solax, recollect_waste, control4, moon, huisbaasje, almond, adax, airly, azure_event_hub, fivem, nws, rtsp_to_webrtc, sentry, webostv, foscam, guardian, twinkly, whirlpool, mysensors, alarmdecoder, ipp, tibber, tomorrowio, slack, ambient_station, netgear, geofency, samsungtv, intellifire, coolmaster, nuki, co2signal, xiaomi_miio, gree, neato, cloudflare, wiffi, aurora, airnow, azure_devops, flux_led, velbus, ovo_energy, pi_hole, aussie_broadband, mikrotik, opentherm_gw, daikin, icloud, switcher_kis, keenetic_ndms2, iqvia, mjpeg, rainmachine, flipr, simplisafe, qnap_qsw, launch_library, lookin, balboa, withings, directv, harmony, lutron_caseta, octoprint, ezviz, traccar, tradfri, buienradar, powerwall, solaredge, tellduslive, wled, meteo_france, zerproc, ondilo_ico, august, tplink, melcloud, rdw, roomba, songpal, picnic, smarttub, nzbget, tautulli, litejet, somfy, airthings, arcam_fmj, adguard, volumio, gios, habitica, onewire, hacs, blink, pure_energie, omnilogic, tankerkoenig, laundrify, mazda, nexia, tailscale, sensibo, steamist, efergy, cpuspeed, philips_js, dlna_dms, synology_dsm, isy994, dexcom, freedompro, fritzbox_callmonitor, trafikverket_train, yeelight, eafm, elgato, minecraft_server, sharkiq, flume, ps4, iss, met_eireann, baf, islamic_prayer_times, openweathermap, environment_canada, trafikverket_weatherstation, broadlink, faa_delays, threshold, vilfo, dynalite, hue, plex, roon, metoffice, risco, subaru, nmap_tracker, local_ip, geonetnz_volcano, tile, esphome, zwave_me, plugwise, bosch_shc, twilio, oncue, progettihwsw, airzone, starline, freebox, enphase_envoy, screenlogic, elmax, coronavirus, wilight, mill, forecast_solar, dunehd, venstar, upnp, goalzero, deluge, aemet, upb, pvoutput, knx, plum_lightpad, yamaha_musiccast, opengarage, google, amberelectric, brother, homematicip_cloud, gpslogger, nightscout, github, hvv_departures, vera, here_travel_time, watttime, unifi, system_bridge, heos, modern_forms, min_max, fronius, abode, renault, dialogflow, gdacs, ambiclimate, vlc_telnet, dsmr, coinbase, bsblan, youless, litterrobot, panasonic_viera, awair, upcloud, ios, derivative, iotawatt, squeezebox, nina, switchbot, vesync, lyric, airtouch4, dnsip, prosegur, devolo_home_network, kostal_plenticore, motioneye, ring, vizio, sms, ruckus_unleashed, tuya, vulcan, nam, advantage_air, integration, rainforest_eagle, forked_daapd, trafikverket_ferry, speedtestdotnet, epson, denonavr, somfy_mylink, geocaching, wiz, canary, **porsche**connect, sonarr, tractive, flick_electric, honeywell, ialarm_xr, agent_dvr, fireservicerota, peco, smappee, rituals_perfume_genie, onvif, cert_expiry, aseko_pool_live, brunt, asuswrt, mutesync, emonitor, elkm1, sleepiq, monoprice, xbox, homekit_controller, season, iaqualink, wolflink, shelly, devolo_home_control, zwave_js, fibaro, senz, nest, fjaraskupan, tolo, kodi, huawei_lte, tasmota, bond, kulersky, juicenet, discord, radio_browser, ipma, tado, generic, glances, braviatv, kraken, emulated_roku, verisure, hlk_sw16, syncthru, switch_as_x, home_connect, steam_online, open_meteo, point, accuweather, transmission, cast, owntracks, sql, nuheat, p1_monitor, goodwe, poolsense, meater, roku, apple_tv, ws66i, airvisual, sia, stookalert, twentemilieu, sense, zha, rachio, logi_circle, enocean, toon, motion_blinds, utility_meter, notion, nut, jellyfin, moehlenhoff_alpha2, nfandroidtv, myq, pvpc_hourly_pricing, mailgun, senseme, xiaomi_aqara, aurora_abb_powerone, sonos, whois, androidtv, garages_amsterdam, home_plus_control, tod, modem_callerid, mobile_app, spider, econet, izone, axis, doorbird, geonetnz_quakes, smart_meter_texas, konnected, fritzbox, locative, sabnzbd, kmtronic, shopping_list, flo, acmeda, homekit, crownstone, sma, plaato, lifx, surepetcare, solarlog, netatmo, growatt_server, srp_energy, vallox, soma, bmw_connected_drive, homewizard, ialarm, fritz, hive, ecobee, wallbox, ifttt, profiler, gogogate2, uptime

> 2022-06-23 21:23:50 DEBUG (SyncWorker_9) [homeassistant.util.json] JSON file not found: /config/custom_components/**porsche**connect/translations/en-GB.json

> 2022-06-23 21:23:51 DEBUG (MainThread) [homeassistant.components.websocket_api.http.connection] [139822996016528] Sending {"id":45,"type":"result","success":true,"result":{"resources":{"component.uptime.title":"Uptime","component.gogogate2.title":"Gogogate2 and ismartgate","component.profiler.title":"Profiler","component.ifttt.title":"IFTTT","component.ecobee.title":"ecobee","component.wallbox.title":"Wallbox","component.hive.title":"Hive","component.fritz.title":"AVM FRITZ!Box Tools","component.ialarm.title":"Antifurto365 iAlarm","component.homewizard.title":"HomeWizard Energy","component.bmw_connected_drive.title":"BMW Connected Drive","component.soma.title":"Soma Connect","component.vallox.title":"Vallox","component.srp_energy.title":"SRP Energy","component.growatt_server.title":"Growatt","component.netatmo.title":"Netatmo","component.solarlog.title":"Solar-Log","component.surepetcare.title":"Sure Petcare","component.lifx.title":"LIFX","component.plaato.title":"Plaato","component.sma.title":"SMA Solar","component.crownstone.title":"Crownstone","component.homekit.title":"HomeKit","component.acmeda.title":"Rollease Acmeda Automate","component.flo.title":"Flo","component.shopping_list.title":"Shopping List","component.kmtronic.title":"KMtronic","component.sabnzbd.title":"SABnzbd","component.locative.title":"Locative","component.fritzbox.title":"AVM FRITZ!SmartHome","component.konnected.title":"Konnected.io","component.smart_meter_texas.title":"Smart Meter Texas","component.geonetnz_quakes.title":"GeoNet NZ Quakes","component.doorbird.title":"DoorBird","component.axis.title":"Axis","component.izone.title":"iZone","component.econet.title":"Rheem EcoNet Products","component.spider.title":"Itho Daalderop Spider","component.mobile_app.title":"Mobile App","component.modem_callerid.title":"Phone Modem","component.tod.title":"Times of the Day","component.home_plus_control.title":"Legrand Home+ Control","component.garages_amsterdam.title":"Garages Amsterdam","component.androidtv.title":"Android TV","component.whois.title":"Whois","component.sonos.title":"Sonos","component.aurora_abb_powerone.title":"Aurora ABB PowerOne Solar PV","component.xiaomi_aqara.title":"Xiaomi Gateway (Aqara)","component.senseme.title":"SenseME","component.mailgun.title":"Mailgun","component.pvpc_hourly_pricing.title":"Spain electricity hourly pricing (PVPC)","component.myq.title":"MyQ","component.nfandroidtv.title":"Notifications for Android TV / Fire TV","component.moehlenhoff_alpha2.title":"M\u00f6hlenhoff Alpha 2","component.jellyfin.title":"Jellyfin","component.nut.title":"Network UPS Tools (NUT)","component.notion.title":"Notion","component.utility_meter.title":"Utility Meter","component.motion_blinds.title":"Motion Blinds","component.toon.title":"Toon","component.enocean.title":"EnOcean","component.logi_circle.title":"Logi Circle","component.rachio.title":"Rachio","component.zha.title":"Zigbee Home Automation","component.sense.title":"Sense","component.twentemilieu.title":"Twente Milieu","component.stookalert.title":"RIVM Stookalert","component.sia.title":"SIA Alarm Systems","component.airvisual.title":"AirVisual","component.ws66i.title":"Soundavo WS66i 6-Zone Amplifier","component.apple_tv.title":"Apple TV","component.roku.title":"Roku","component.meater.title":"Meater","component.poolsense.title":"PoolSense","component.goodwe.title":"GoodWe Inverter","component.p1_monitor.title":"P1 Monitor","component.nuheat.title":"NuHeat","component.sql.title":"SQL","component.owntracks.title":"OwnTracks","component.cast.title":"Google Cast","component.transmission.title":"Transmission","component.accuweather.title":"AccuWeather","component.point.title":"Minut Point","component.open_meteo.title":"Open-Meteo","component.steam_online.title":"Steam","component.home_connect.title":"Home Connect","component.switch_as_x.title":"Switch as X","component.syncthru.title":"Samsung SyncThru Printer","component.hlk_sw16.title":"Hi-Link HLK-SW16","component.verisure.title":"Verisure","component.emulated_roku.title":"Emulated Roku","component.kraken.title":"Kraken","component.braviatv.title":"Sony Bravia TV","component.glances.title":"Glances","component.generic.title":"Generic Camera","component.tado.title":"Tado","component.ipma.title":"Instituto Portugu\u00eas do Mar e Atmosfera (IPMA)","component.radio_browser.title":"Radio Browser","component.discord.title":"Discord","component.juicenet.title":"JuiceNet","component.kulersky.title":"Kuler Sky","component.bond.title":"Bond","component.tasmota.title":"Tasmota","component.huawei_lte.title":"Huawei LTE","component.kodi.title":"Kodi","component.tolo.title":"TOLO Sauna","component.fjaraskupan.title":"Fj\u00e4r\u00e5skupan","component.nest.title":"Nest","component.senz.title":"nVent RAYCHEM SENZ","component.fibaro.title":"Fibaro","component.zwave_js.title":"Z-Wave JS","component.devolo_home_control.title":"devolo Home Control","component.shelly.title":"Shelly","component.wolflink.title":"Wolf SmartSet Service","component.iaqualink.title":"Jandy iAqualink","component.season.title":"Season","component.homekit_controller.title":"HomeKit Controller","component.xbox.title":"Xbox","component.monoprice.title":"Monoprice 6-Zone Amplifier","component.sleepiq.title":"SleepIQ","component.elkm1.title":"Elk-M1 Control","component.emonitor.title":"SiteSage Emonitor","component.mutesync.title":"mutesync","component.asuswrt.title":"ASUSWRT","component.brunt.title":"Brunt Blind Engine","component.aseko_pool_live.title":"Aseko Pool Live","component.cert_expiry.title":"Certificate Expiry","component.onvif.title":"ONVIF","component.rituals_perfume_genie.title":"Rituals Perfume Genie","component.smappee.title":"Smappee","component.peco.title":"PECO Outage Counter","component.fireservicerota.title":"FireServiceRota","component.agent_dvr.title":"Agent DVR","component.ialarm_xr.title":"Antifurto365 iAlarmXR","component.honeywell.title":"Honeywell Total Connect Comfort (US)","component.flick_electric.title":"Flick Electric","component.tractive.title":"Tractive","component.sonarr.title":"Sonarr","component.**porsche**connect.title":"**Porsche** Connect","component.canary.title":"Canary","component.wiz.title":"WiZ","component.geocaching.title":"Geocaching","component.somfy_mylink.title":"Somfy MyLink","component.denonavr.title":"Denon AVR Network Receivers","component.epson.title":"Epson","component.speedtestdotnet.title":"Speedtest.net","component.trafikverket_ferry.title":"Trafikverket Ferry","component.forked_daapd.title":"forked-daapd","component.rainforest_eagle.title":"Rainforest Eagle","component.integration.title":"Integration - Riemann sum integral","component.advantage_air.title":"Advantage Air","component.nam.title":"Nettigo Air Monitor","component.vulcan.title":"Uonet+ Vulcan","component.tuya.title":"Tuya","component.ruckus_unleashed.title":"Ruckus Unleashed","component.sms.title":"SMS notifications via GSM-modem","component.vizio.title":"VIZIO SmartCast","component.ring.title":"Ring","component.motioneye.title":"motionEye","component.kostal_plenticore.title":"Kostal Plenticore Solar Inverter","component.devolo_home_network.title":"devolo Home Network","component.prosegur.title":"Prosegur Alarm","component.dnsip.title":"DNS IP","component.airtouch4.title":"AirTouch 4","component.lyric.title":"Honeywell Lyric","component.vesync.title":"VeSync","component.switchbot.title":"SwitchBot","component.nina.title":"NINA","component.squeezebox.title":"Squeezebox (Logitech Media Server)","component.iotawatt.title":"IoTaWatt","component.derivative.title":"Derivative","component.ios.title":"Home Assistant iOS","component.upcloud.title":"UpCloud","component.awair.title":"Awair","component.panasonic_viera.title":"Panasonic Viera","component.litterrobot.title":"Litter-Robot","component.youless.title":"YouLess","component.bsblan.title":"BSB-Lan","component.coinbase.title":"Coinbase","component.dsmr.title":"DSMR Slimme Meter","component.vlc_telnet.title":"VLC media player via Telnet","component.ambiclimate.title":"Ambiclimate","component.gdacs.title":"Global Disaster Alert and Coordination System (GDACS)","component.dialogflow.title":"Dialogflow","component.renault.title":"Renault","component.abode.title":"Abode","component.fronius.title":"Fronius","component.min_max.title":"Min/Max","component.modern_forms.title":"Modern Forms","component.heos.title":"Denon HEOS","component.system_bridge.title":"System Bridge","component.unifi.title":"UniFi Network","component.watttime.title":"WattTime","component.here_travel_time.title":"HERE Travel Time","component.vera.title":"Vera","component.hvv_departures.title":"HVV Departures","component.github.title":"GitHub","component.nightscout.title":"Nightscout","component.gpslogger.title":"GPSLogger","component.homematicip_cloud.title":"HomematicIP Cloud","component.brother.title":"Brother Printer","component.amberelectric.title":"Amber Electric","component.google.title":"Google Calendars","component.opengarage.title":"OpenGarage","component.yamaha_musiccast.title":"MusicCast","component.plum_lightpad.title":"Plum Lightpad","component.knx.title":"KNX","component.pvoutput.title":"PVOutput","component.upb.title":"Universal Powerline Bus (UPB)","component.aemet.title":"AEMET OpenData","component.deluge.title":"Deluge","component.goalzero.title":"Goal Zero Yeti","component.upnp.title":"UPnP/IGD","component.venstar.title":"Venstar","component.dunehd.title":"Dune HD","component.forecast_solar.title":"Forecast.Solar","component.mill.title":"Mill","component.wilight.title":"WiLight","component.coronavirus.title":"Coronavirus (COVID-19)","component.elmax.title":"Elmax","component.screenlogic.title":"Pentair ScreenLogic","component.enphase_envoy.title":"Enphase Envoy","component.freebox.title":"Freebox","component.starline.title":"StarLine","component.airzone.title":"Airzone","component.progettihwsw.title":"ProgettiHWSW Automation","component.oncue.title":"Oncue by Kohler","component.twilio.title":"Twilio","component.bosch_shc.title":"Bosch SHC","component.plugwise.title":"Plugwise","component.zwave_me.title":"Z-Wave.Me","component.esphome.title":"ESPHome","component.tile.title":"Tile","component.geonetnz_volcano.title":"GeoNet NZ Volcano","component.local_ip.title":"Local IP Address","component.nmap_tracker.title":"Nmap Tracker","component.subaru.title":"Subaru","component.risco.title":"Risco","component.metoffice.title":"Met Office","component.roon.title":"RoonLabs music player","component.plex.title":"Plex Media Server","component.hue.title":"Philips Hue","component.dynalite.title":"Philips Dynalite","component.vilfo.title":"Vilfo Router","component.threshold.title":"Threshold","component.faa_delays.title":"FAA Delays","component.broadlink.title":"Broadlink","component.trafikverket_weatherstation.title":"Trafikverket Weather Station","component.environment_canada.title":"Environment Canada","component.openweathermap.title":"OpenWeatherMap","component.islamic_prayer_times.title":"Islamic Prayer Times","component.baf.title":"Big Ass Fans","component.met_eireann.title":"Met \u00c9ireann","component.iss.title":"International Space Station (ISS)","component.ps4.title":"Sony PlayStation 4","component.flume.title":"Flume","component.sharkiq.title":"Shark IQ","component.minecraft_server.title":"Minecraft Server","component.elgato.title":"Elgato Light","component.eafm.title":"Environment Agency Flood Gauges","component.yeelight.title":"Yeelight","component.trafikverket_train.title":"Trafikverket Train","component.fritzbox_callmonitor.title":"AVM FRITZ!Box Call Monitor","component.freedompro.title":"Freedompro","component.dexcom.title":"Dexcom","component.isy994.title":"Universal Devices ISY994","component.synology_dsm.title":"Synology DSM","component.dlna_dms.title":"DLNA Digital Media Server","component.philips_js.title":"Philips TV","component.cpuspeed.title":"CPU Speed","component.efergy.title":"Efergy","component.steamist.title":"Steamist","component.sensibo.title":"Sensibo","component.tailscale.title":"Tailscale","component.nexia.title":"Nexia/American Standard/Trane","component.mazda.title":"Mazda Connected Services","component.laundrify.title":"laundrify","component.tankerkoenig.title":"Tankerkoenig","component.omnilogic.title":"Hayward Omnilogic","component.pure_energie.title":"Pure Energie","component.blink.title":"Blink","component.hacs.title":"HACS","component.onewire.title":"1-Wire","component.habitica.title":"Habitica","component.gios.title":"GIO\u015a","component.volumio.title":"Volumio","component.adguard.title":"AdGuard Home","component.arcam_fmj.title":"Arcam FMJ Receivers","component.airthings.title":"Airthings","component.somfy.title":"Somfy","component.litejet.title":"LiteJet","component.tautulli.title":"Tautulli","component.nzbget.title":"NZBGet","component.smarttub.title":"SmartTub","component.picnic.title":"Picnic","component.songpal.title":"Sony Songpal","component.roomba.title":"iRobot Roomba and Braava","component.rdw.title":"RDW","component.melcloud.title":"MELCloud","component.tplink.title":"TP-Link Kasa Smart","component.august.title":"August","component.ondilo_ico.title":"Ondilo ICO","component.zerproc.title":"Zerproc","component.meteo_france.title":"M\u00e9t\u00e9o-France","component.wled.title":"WLED","component.tellduslive.title":"Telldus Live","component.solaredge.title":"SolarEdge","component.powerwall.title":"Tesla Powerwall","component.buienradar.title":"Buienradar","component.tradfri.title":"IKEA TR\u00c5DFRI","component.traccar.title":"Traccar","component.ezviz.title":"Ezviz","component.octoprint.title":"OctoPrint","component.lutron_caseta.title":"Lutron Cas\u00e9ta","component.harmony.title":"Logitech Harmony Hub","component.directv.title":"DirecTV","component.withings.title":"Withings","component.balboa.title":"Balboa Spa Client","component.lookin.title":"LOOKin","component.launch_library.title":"Launch Library","component.qnap_qsw.title":"QNAP QSW","component.simplisafe.title":"SimpliSafe","component.flipr.title":"Flipr","component.rainmachine.title":"RainMachine","component.mjpeg.title":"MJPEG IP Camera","component.iqvia.title":"IQVIA","component.keenetic_ndms2.title":"Keenetic NDMS2 Router","component.switcher_kis.title":"Switcher","component.icloud.title":"Apple iCloud","component.daikin.title":"Daikin AC","component.opentherm_gw.title":"OpenTherm Gateway","component.mikrotik.title":"Mikrotik","component.aussie_broadband.title":"Aussie Broadband","component.pi_hole.title":"Pi-hole","component.ovo_energy.title":"OVO Energy","component.velbus.title":"Velbus","component.flux_led.title":"Magic Home","component.azure_devops.title":"Azure DevOps","component.airnow.title":"AirNow","component.aurora.title":"Aurora","component.wiffi.title":"Wiffi","component.cloudflare.title":"Cloudflare","component.neato.title":"Neato Botvac","component.gree.title":"Gree Climate","component.xiaomi_miio.title":"Xiaomi Miio","component.co2signal.title":"CO2 Signal","component.nuki.title":"Nuki","component.coolmaster.title":"CoolMasterNet","component.intellifire.title":"IntelliFire","component.samsungtv.title":"Samsung Smart TV","component.geofency.title":"Geofency","component.netgear.title":"NETGEAR","component.ambient_station.title":"Ambient Weather Station","component.slack.title":"Slack","component.tomorrowio.title":"Tomorrow.io","component.tibber.title":"Tibber","component.ipp.title":"Internet Printing Protocol (IPP)","component.alarmdecoder.title":"AlarmDecoder","component.mysensors.title":"MySensors","component.whirlpool.title":"Whirlpool Sixth Sense","component.twinkly.title":"Twinkly","component.guardian.title":"Elexa Guardian","component.foscam.title":"Foscam","component.webostv.title":"LG webOS Smart TV","component.sentry.title":"Sentry","component.rtsp_to_webrtc.title":"RTSPtoWebRTC","component.nws.title":"National Weather Service (NWS)","component.fivem.title":"FiveM","component.azure_event_hub.title":"Azure Event Hub","component.airly.title":"Airly","component.adax.title":"Adax","component.almond.title":"Almond","component.huisbaasje.title":"Huisbaasje","component.moon.title":"Moon","component.control4.title":"Control4","component.recollect_waste.title":"ReCollect Waste","component.solax.title":"SolaX Power","component.google_travel_time.title":"Google Maps Travel Time","component.vicare.title":"Viessmann ViCare","component.kaleidescape.title":"Kaleidescape","component.hyperion.title":"Hyperion","component.luftdaten.title":"Sensor.Community","component.life360.title":"Life360","component.hisense_aehw4a1.title":"Hisense AEH-W4A1","component.flunearyou.title":"Flu Near You","component.openuv.title":"OpenUV","component.slimproto.title":"SlimProto (Squeezebox players)","component.hunterdouglas_powerview.title":"Hunter Douglas PowerView","component.atag.title":"Atag","component.spotify.title":"Spotify","component.deconz.title":"deCONZ","component.rfxtrx.title":"RFXCOM RFXtrx","component.ridwell.title":"Ridwell","component.wemo.title":"Belkin WeMo","component.yale_smart_alarm.title":"Yale Smart Living","component.meteoclimatic.title":"Meteoclimatic","component.ambee.title":"Ambee","component.uptimerobot.title":"UptimeRobot","component.evil_genius_labs.title":"Evil Genius Labs","component.version.title":"Version","component.smartthings.title":"SmartThings","component.overkiz.title":"Overkiz (by Somfy)","component.yolink.title":"YoLink","component.tesla_wall_connector.title":"Tesla Wall Connector","component.totalconnect.title":"Total Connect","component.mullvad.title":"Mullvad VPN","component.waze_travel_time.title":"Waze Travel Time","component.aladdin_connect.title":"Aladdin Connect","component.insteon.title":"Insteon","component.filesize.title":"File Size","component.blebox.title":"BleBox devices","component.unifiprotect.title":"UniFi Protect","component.ukraine_alarm.title":"Ukraine Alarm","component.hangouts.title":"Google Chat","component.smhi.title":"SMHI","component.nanoleaf.title":"Nanoleaf","component.syncthing.title":"Syncthing"}}}

>2022-06-23 21:23:52 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-**porsche**connect> Getting repository information

>2022-06-23 21:23:52 DEBUG (MainThread) [custom_components.hacs] <Integration CJNE/ha-**porsche**connect> Running checks against 0.0.8

**Comment by CJNE** [comment]
Hi, sorry for the late response! Is this still an issue or can I close this?

**Comment by sdds250** [comment]
Hi, this is not an issueanymore, I don’t know how and why it started to show up at a certain point.However, as you seems tobe active now, after some month of usage, it doesn’t seemto connect anymore, all my sensors arr ‘unavailable’Do you want me to create a new issue?Thanks for your contribution via this plugin!RegardsOn 23 Nov 2022, at 21:49, Johan Isacsson ***@***.***> wrote:﻿
Hi, sorry for the late response! Is this still an issue or can I close this?

**Comment by CJNE** [comment]
If the problem persists please open a new issue, closing this for now.
